export default function Legal(){
    return(
        <>
        <div className="bg-primary outline rounded-2xl outline-2 outline-secondary overflow-hidden shadow-sp">
            <div className="h-auto w-full bg-secondary p-3 text-white text-md outline-secondary outline outline-5"><h2 className="text-md">Legal Disclaimers</h2></div>
                <div className="p-4 text-white text-xs">

                        <p className="font-bold py-3">
                        NCSOFT, the interlocking NC logo, ArenaNet, Guild Wars, Guild Wars Factions, Guild Wars Nightfall, Guild Wars: Eye of the North, Guild Wars 2, and all associated logos and designs are trademarks or registered trademarks of NCSOFT Corporation. All other trademarks are the property of their respective owners.
                        </p>

                        <p className="py-1">If you require any more information or have any questions about our site's disclaimer, please feel free to contact us by email at alexander@konrads.io. Our Disclaimer was generated with the help of the <a href="https://www.termsfeed.com/disclaimer-generator/">Disclaimer Generator</a>.</p>

                        <h2 className="font-bold py-1 pt-3">TL;DR</h2>
                        <p className="py-1">We do not save any of your account information to our servers. We save a copy of your account data to your local browser to allow you to search it quickly. We use Google Analytics to gauge traffic. We are not liable for content found on websites that might be linked from this website. We only provide links in good faith and try to quickly detect links that have gone bad.</p>
                        <h2 className="font-bold py-1 pt-3">Disclaimers for FindMySkritt.com</h2>

                        <p className="py-1">All the information on this website - FindMySkritt.com - is published in good faith and for general information purpose only. FindMySkritt.com does not make any warranties about the completeness, reliability and accuracy of this information. Any action you take upon the information you find on this website (FindMySkritt.com), is strictly at your own risk. FindMySkritt.com will not be liable for any losses and/or damages in connection with the use of our website.</p>

                        <p className="py-1">FindMySkritt.com uses cookies in order to store some of your provided information locally on your device to improve operational quality and reduce server load. The saved data consist of a mirror of the items on your account and your api key but no data that would allow authentication on other websites or allow access to your account directly.</p>

                        <p className="py-1">FindMySkritt.com does not store any of your data on it's own servers and does not provide any other services with access to any data entered on this website.</p>

                        <p className="py-1">From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone 'bad'.</p>

                        <p className="py-1">Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.</p>

                        <h2 className="font-bold py-1">Consent</h2>

                        <p className="py-1">By using our website, you hereby consent to our disclaimer and agree to its terms.</p>

                        <h2 className="font-bold py-1">Google Analytics</h2>
                        
                        <p className="py-1">
                        This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. In case of activation of the IP anonymization, Google will truncate/anonymize the last octet of the IP address for Member States of the European Union as well as for other parties to the Agreement on the European Economic Area. Only in exceptional cases, the full IP address is sent to and shortened by Google servers in the USA. On behalf of the website provider Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage to the website provider. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website. Furthermore you can prevent Google’s collection and use of data (cookies and IP address) by downloading and installing the browser plug-in available under https://tools.google.com/dlpage/gaoptout?hl=en-GB.
                        </p>

                        <h2 className="font-bold py-1">Update</h2>

                        <p className="py-1">Should we update, amend or make any changes to this document, those changes will be prominently posted here.</p>

                       
            </div>
        </div>

        </>
    )
}